version: '3'

services:
    cwskimmer:
        #build: .
        image: ghcr.io/8ch9azbsfifz/docker-cwskimmer:latest
        network_mode: host   
        privileged: true

        environment:
            - QTH=KA12aa
            - NAME="Mr. X"
            - CALLSIGN=CW0SKIM
            - IP_HERMES=10.101.44.120
            - SQUARE=KA12aa
        #ports:
        #    - 8080:8080
        #    - 7301:7300
        #    - 9001:9001
